apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: shopnow
  labels:
    app: product-service
    part-of: shopnow
    version: "1.0"
spec:
  selector:
    app: product-service
  ports:
    - port: 8081
      targetPort: 8081