apiVersion: v1
kind: Service
metadata:
  name: discovery-server-external
  namespace: shopnow
spec:
  type: NodePort
  selector:
    app: discovery-server
  ports:
    - port: 8761
      targetPort: 8761
      nodePort: 30761
