apiVersion: v1
kind: Service
metadata:
  name: postgres-inventory
  namespace: shopnow
spec:
  clusterIP: None       # Headless â€” no virtual IP, DNS resolves to Pod IPs directly
  selector:
    app: postgres-inventory
  ports:
    - port: 5432
      targetPort: 5432