apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-inventory
  namespace: shopnow
  labels:
    app: postgres-inventory
    part-of: shopnow
spec:
  serviceName: postgres-inventory    # Must match the Headless Service name below
  replicas: 1
  selector:
    matchLabels:
      app: postgres-inventory
  template:
    metadata:
      labels:
        app: postgres-inventory
        part-of: shopnow
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: inventory-db-credentials
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
  volumeClaimTemplates:          # K8s creates a PVC for each Pod automatically
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard   # Minikube default
        resources:
          requests:
            storage: 1Gi